apiVersion: apps/v1
kind: Deployment
metadata:
    name: flask-app
spec:
    selector:
        matchLabels:
            app: flask-web
    template:
       metadata:
          labels:
            app: flask-web
       spec:
         containers:
         - name: py-demo
           image: docker.io/vishnusk/py-demo:latest
           ports:
           - containerPort: 5000
           volumeMounts:
           - name: name-volume
           mountPath: /opt/config
        volumes:
        -  name: name-volume
           configMap:
             name: my-name